### ISSUE TITLE
Okhttp Websocket client crashes Android application when websocket fails

### ISSUE THREAD

**Issue by varahash** [ktorio/ktor#1356]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-client-okhttp:1.2.4

**Describe the bug**
The app crashes at this line: https://github.com/ktorio/ktor/blob/1.2.4/ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt#L53
Because we close outgoing actor channel with exception here: https://github.com/ktorio/ktor/blob/1.2.4/ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt#L98
the actor fails to read next frame and rethrow this exception up. But there is no exception handlers, so by default unhandled exception in coroutines leads to Android app crash.

**Comment by varahash** [comment]
Is any chance to get fix in 1.3.0 release?

**Comment by e5l** [comment]
Could you reproduce it with `1.3.0-rc2`? It should be fixed with top level exception handler for the client.

**Comment by varahash** [comment]
@e5l You're right, after you added global exception handler `SilentSupervisor` in https://github.com/ktorio/ktor/commit/93c4543fc77a32c5d159b79380d64ac5eb02292e
Application crash not happens.
BTW: Do you think that this approach with silently ignoring exceptions is good? Maybe it's better at least to log them, and later we can fix root causes of such exceptions in first place.

**Comment by e5l** [comment]
Thanks for the notice @varahash, but the exception is not ignored. It also propagates in `continuation.resumeWithException`, the ignored exception doubled because of Job cancellation(with the same exception) and shouldn't be propagated.

**Comment by edenman** [comment]
I'm still getting app crashes from OkHttp exceptions, do I need to do anything special to get the global exception handler? https://youtrack.jetbrains.com/issue/KTOR-870
