### ISSUE TITLE
[Bug] Cancel flow of SSESession.incoming will not disconnect connection in OkHttpSSESession implementation

### ISSUE THREAD

**Issue by hehua2008** [ktorio/ktor#4692]
Look at these source code.
In the OkHttpSSESession implementation of SSESession, cancel incoming flow will **not** trigger serverSentEventsSource.cancel(), which will keep SSE still connecting !

```kotlin
internal class OkHttpSSESession(
    engine: OkHttpClient,
    engineRequest: Request,
    override val coroutineContext: CoroutineContext,
) : SSESession, EventSourceListener() {
    private val serverSentEventsSource = EventSources.createFactory(engine).newEventSource(engineRequest, this)

    ...

    private val _incoming = Channel<ServerSentEvent>(8)

    override val incoming: Flow<ServerSentEvent>
        get() = _incoming.receiveAsFlow()

    ...

    override fun onEvent(eventSource: EventSource, id: String?, type: String?, data: String) {
        _incoming.trySendBlocking(ServerSentEvent(data, type, id))
    }

    override fun onFailure(eventSource: EventSource, t: Throwable?, response: Response?) {
        ...

        _incoming.close()
        serverSentEventsSource.cancel()
    }

    override fun onClosed(eventSource: EventSource) {
        _incoming.close()
        serverSentEventsSource.cancel()
    }
}
```

But in the DefaultClientSSESession implementation of SSESession, cancel incoming flow will trigger coroutineContext.cancel() and input.cancel(), which will disconnect SSE connection !
```kotlin
@OptIn(InternalAPI::class)
@Deprecated("It should be marked with `@InternalAPI`, please use `ClientSSESession` instead")
public class DefaultClientSSESession(
    content: SSEClientContent,
    private var input: ByteReadChannel,
    override val coroutineContext: CoroutineContext
) : SSESession {
    ...

    public constructor(
        content: SSEClientContent,
        input: ByteReadChannel
    ) : this(content, input, content.callContext + Job() + CoroutineName("DefaultClientSSESession"))

    private var _incoming = flow {
        // inner while for parsing events of current input (=connection), and when the current input is closed,
        // we have an outer while to obtain new input
        while (this@DefaultClientSSESession.coroutineContext.isActive) {
            while (this@DefaultClientSSESession.coroutineContext.isActive) {
                val event = input.parseEvent() ?: break

                if (event.isCommentsEvent() && !showCommentEvents) continue
                if (event.isRetryEvent() && !showRetryEvents) continue

                emit(event)
            }

            if (needToReconnect) {
                doReconnection()
            } else {
                close()
            }
        }
    }.catch { cause ->
        when (cause) {
            is CancellationException -> {
                close()
            }

            else -> {
                LOGGER.trace { "Error during SSE session processing: $cause" }
                close()
                throw cause
            }
        }
    }

    init {
        coroutineContext.job.invokeOnCompletion {
            close()
        }
    }

    private suspend fun doReconnection() {
        ...
    }

    ...

    override val incoming: Flow<ServerSentEvent>
        get() = _incoming

    private fun close() {
        coroutineContext.cancel()
        input.cancel()
    }

    ....
}
```

**Comment by Stexxe** [comment]
Can you please share a code snippet to reproduce the problem?

**Comment by hehua2008** [comment]
> Can you please share a code snippet to reproduce the problem?

Sorry, but it is hard to provide a code snippet of SSE connection, since we need to write SSE server code too.

I have submitted a pull request: https://github.com/ktorio/ktor/pull/4694
The solution is clear and simple. It works well for my project.
You can either review the PR or provide a better solution~😊

**Comment by hehua2008** [comment]
And there is a similar bug on iOS and I don't know how to fix it yet.

**Comment by hehua2008** [comment]
> Can you please share a code snippet to reproduce the problem?

I have fixed the similar bug in DefaultClientSSESession in https://github.com/ktorio/ktor/pull/4694

And I have added testCancelSseSession in ServerSentEventsTest for ktor-client:
```kotlin
    @Test
    fun testCancelSseSession() = clientTests {
        config {
            install(SSE)
        }

        test { client ->
            coroutineScope {
                val job = launch {
                    val session = client.serverSentEventsSession("$TEST_SERVER/sse/hello?times=20&interval=100")
                    try {
                        session.incoming.collect()
                    } finally {
                        withContext(NonCancellable) {
                            delay(500)
                            assertFalse(session.isActive)
                        }
                    }
                }
                delay(500)
                job.cancelAndJoin()
            }
        }
    }
```

**Comment by e5l** [comment]
Merged! Thank you for the contribution

**Comment by osipxd** [comment]
YouTrack: [KTOR-8244](https://youtrack.jetbrains.com/issue/KTOR-8244)

**Comment by Savrov** [comment]
Hi @e5l, it's me again 😅

I'm currently testing version **3.1.2**, and while things are working great on **Android** (with the OkHttp engine), I’m still facing a problem on **iOS** (with the Darwin engine).

## ✅ Android behavior (OkHttp)

- Connection is established successfully  
- The backend sends `ping` events regularly  
- When I close the connection on the client side, the server immediately detects it (verified in Kibana logs) and considers the connection inactive  
- Our backend enforces a **limit of 5 connections per device**, but Android handles it perfectly since it closes obsolete connections promptly  

## ❌ iOS behavior (Darwin)

- The exact same code is used  
- However, after several reconnections, I get **429 errors** from the backend: _"Too Many Requests / Connections"_  
- According to backend logs, previous connections are **not properly closed** from the server’s perspective  
- Eventually, the server blocks the client for exceeding the 5-connection limit  

---

Could this be an issue with the Darwin engine not properly terminating the connection?  
Again, the **same client logic** works flawlessly on Android, but seems to behave differently on iOS.

Let me know if I can provide more debug info — thanks a lot in advance! 🙏

**Comment by e5l** [comment]
Hey! Thank you for the report. We will check

**Comment by Savrov** [comment]
### 🔁 How SSE client is used

```kotlin
    public fun observe(
        ttId: String?,
        serviceId: String?,
    ): Flow<ServerSentEvent> = callbackFlow {
        this@ChatSseClient.logD("SSE: start flow")
        val reconnectJob = launch {
            while (isActive) {
                try {
                    authorizedSseClient.client.sse(
                        reconnectionTime = 1.seconds,

                        request = {
                            url {
                                host = serverProvider.getCurrentHost()
                                path(PATH_ONLINE_NOTIFICATIONS)
                                parameter(QUERY_PARAM_TT_ID, ttId)
                                parameter(QUERY_PARAM_SERVICE_ID, serviceId)
                            }
                        }
                    ) {
                        incoming
                            .onStart { this@ChatSseClient.logD("SSE onStart") }
                            .onEach {
                                this@ChatSseClient.logD("SSE onEach=$it")
                                send(it)
                            }
                            .catch { exception ->
                                val event = getEventFromThrowable(exception)
                                this@ChatSseClient.logD("SSE onException=$exception")
                                event?.let { send(it) }
                            }
                            .onCompletion { exception ->
                                this@ChatSseClient.logD("SSE onCompletion=$exception")
                            }
                            .collect()
                    }

                    this@ChatSseClient.logD("SSE finished normally")
                } catch (e: Exception) {
                    if (!isActive) break
                    this@ChatSseClient.logD("SSE exception outside flow: $e")
                    val event = getEventFromThrowable(e)
                    event?.let { send(it) }
                }

                delay(1.seconds)
            }
        }

        reconnectJob.invokeOnCompletion {
            this@ChatSseClient.logD("SSE: reconnect job completed: $it")
        }

        awaitClose {
            this@ChatSseClient.logD("SSE: awaitClose called")
            reconnectJob.cancel()
        }
    }
```

### 🔌 connect() and disconnect() implementation
```kotlin
private var job: Job? = null
private var scope: CoroutineScope? = null

override suspend fun connect() {
    logD("Connecting to SSE")

    // Cancel previous SSE session
    disconnect()  // used as a safeguard here

    // Slight delay before reconnecting
    delay(5000)

    scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    job = scope?.launch {
        sseClient.observe(
            ttId = getDestination()?.ttId,
            serviceId = getDestination()?.serviceId,
        ).collect { event ->
            handleSseEvent(event)
        }

        logD("SSE observation is completed")
    }
}

override fun disconnect() {
    logD("Disconnecting from SSE")
    scope?.cancel()
    job?.cancel()
    job = null
}
```

> ☝️ Important note:
> disconnect() is explicitly called when the user leaves the chat screen (i.e. onDisappear() in the ViewModel).
> Calling it again inside connect() is just a safety measure to avoid overlapping sessions.

This approach guarantees (as i understand it):
	•	No more than 1 active SSE connection.
	•	Previous jobs and scopes are cancelled.

**Comment by marychatte** [comment]
Hi @Savrov, I'm trying to reproduce the bug, can you please clarify some moments:
1. Why you need `val reconnectJob` in your code? Do you use the sse reconnection? (does the `maxReconnectionAttempts` set in SSE plugin?)
2. _"According to backend logs, previous connections are not properly closed from the server’s perspective"_ - do you mean client sends reconnection requests to server?
