### ISSUE TITLE
Error in build IOS project

### ISSUE THREAD

**Issue by MohamedTaher** [ktorio/ktor#820]
### Ktor Version
Ktor Version 1.0.0

### Ktor Engine Used
```
implementation "io.ktor:ktor-client-core:$ktor_version"
implementation "io.ktor:ktor-client-json:$ktor_version"

implementation "io.ktor:ktor-client-core-jvm:$ktor_version"
implementation "io.ktor:ktor-client-json-jvm:$ktor_version"

implementation "io.ktor:ktor-client-core-ios:$ktor_version"
implementation "io.ktor:ktor-client-ios:$ktor_version"
implementation "io.ktor:ktor-client-json-ios:$ktor_version"
```

### JVM Version, Operating System and Relevant Context
JVM Version 1.8.0_192
Operating System MacOS Majave Version 1.014
Xcode Version 10.1

### Feedback
I created a IOS/Android project using intelij Idea then i call an api and it's working successfully in Android but in IOS it didn't work

The code 
```
//Common Main
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.http.*
import kotlinx.coroutines.*

//internal expect val ApplicationDispatcher: CoroutineDispatcher

class ApplicationApi {
    private val client = HttpClient()

    var address = Url("https://tools.ietf.org/rfc/rfc1866.txt")

    fun about(callback: (String) -> Unit) {
        GlobalScope.apply {
            launch {
                try {
                    val result: String = client.get {
                        url(this@ApplicationApi.address.toString())
                    }

                    callback(result)
                } catch (e: Exception) {
                    callback("Timeout")
                }

            }
        }
    }
}
```
```
//app gradle 
plugins {
    id 'kotlin-multiplatform' version '1.3.10'
}
repositories {
    google()
    jcenter()
    mavenCentral()
}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: "kotlinx-serialization"

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "org.jetbrains.kotlin.mpp_app_android"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'

    implementation("com.android.support:recyclerview-v7:28.0.0")
    implementation("com.jakewharton.timber:timber-android:5.0.0-k1.3.0-a1")
    implementation("io.ktor:ktor-client-json-jvm:1.0.0")
    implementation("io.ktor:ktor-client-okhttp:1.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.1")
}

kotlin {
    targets {
        fromPreset(presets.android, 'android')
        // This preset is for iPhone emulator
        // Switch here to presets.iosArm64 (or iosArm32) to build library for iPhone device
        fromPreset(presets.iosX64, 'ios') {
            compilations.main.outputKinds('FRAMEWORK')
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
                
                implementation "com.jakewharton.timber:timber-common:$timber_version"
                implementation "io.ktor:ktor-client-core:$ktor_version"
                implementation "io.ktor:ktor-client-json:$ktor_version"
                implementation "org.jetbrains.kotlin:kotlin-stdlib"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
                implementation "org.kodein.di:kodein-di-core:$kodein_version"
                implementation "org.kodein.di:kodein-di-erased:$kodein_version"
            }
        }
        commonTest {
            dependencies {
        		implementation 'org.jetbrains.kotlin:kotlin-test-common'
        		implementation 'org.jetbrains.kotlin:kotlin-test-annotations-common'
            }
        }
        androidMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib'
                
                implementation "com.jakewharton.timber:timber-jdk:$timber_version"
                implementation "io.ktor:ktor-client-core-jvm:$ktor_version"
                implementation "io.ktor:ktor-client-json-jvm:$ktor_version"
                implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
            }
        }
        androidTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test'
                implementation 'org.jetbrains.kotlin:kotlin-test-junit'
            }
        }
        iosMain {
            dependencies {
                implementation "com.jakewharton.timber:timberNative:$timber_version"
                implementation "io.ktor:ktor-client-core-ios:$ktor_version"
                implementation "io.ktor:ktor-client-ios:$ktor_version"
                implementation "io.ktor:ktor-client-json-ios:$ktor_version"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutines_version"
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
            }
        }
        iosTest {
        }
    }
}

// This task attaches native framework built from ios module to Xcode project
// (see iosApp directory). Don't run this task directly,
// Xcode runs this task itself during its build process.
// Before opening the project from iosApp directory in Xcode,
// make sure all Gradle infrastructure exists (gradle.wrapper, gradlew).
task copyFramework {
    def buildType = project.findProperty("kotlin.build.type") ?: "DEBUG"
    def target = project.findProperty("kotlin.target") ?: "ios"
    dependsOn "link${buildType.toLowerCase().capitalize()}Framework${target.capitalize()}"

    doLast {
        def srcFile = kotlin.targets."$target".compilations.main.getBinary("FRAMEWORK", buildType)
        def targetDir = getProperty("configuration.build.dir")
        copy {
            from srcFile.parent
            into targetDir
            include 'app.framework/**'
            include 'app.framework.dSYM'
        }
    }
}
```
```
//project gradle 
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "com.android.tools.build:gradle:$gradle_android_version"
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url "https://dl.bintray.com/kotlin/ktor" }
        maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }
        maven { url "https://dl.bintray.com/touchlabpublic/kotlin" }
        maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
    }
}
```

I got this error when i tried to build the IOS project in Xcode
```
> Task :app:linkDebugFrameworkIos FAILED
app/src/commonMain/kotlin/sample/Sample.kt:3:8: error: unresolved reference: io
import io.ktor.client.*
       ^
app/src/commonMain/kotlin/sample/Sample.kt:4:8: error: unresolved reference: io
import io.ktor.client.request.*
       ^
app/src/commonMain/kotlin/sample/Sample.kt:5:8: error: unresolved reference: io
import io.ktor.http.*
       ^
app/src/commonMain/kotlin/sample/Sample.kt:6:16: error: unresolved reference: coroutines
import kotlinx.coroutines.*
               ^
app/src/commonMain/kotlin/sample/Sample.kt:11:26: error: unresolved reference: HttpClient
    private val client = HttpClient()
                         ^
app/src/commonMain/kotlin/sample/Sample.kt:13:19: error: unresolved reference: Url
    var address = Url("https://tools.ietf.org/rfc/rfc1866.txt")
                  ^
app/src/commonMain/kotlin/sample/Sample.kt:16:9: error: unresolved reference: GlobalScope
        GlobalScope.apply {
        ^
app/src/commonMain/kotlin/sample/Sample.kt:17:13: error: unresolved reference: launch
            launch {
            ^
app/src/commonMain/kotlin/sample/Sample.kt:20:25: error: unresolved reference: url
                        url(this@ApplicationApi.address.toString())
                        ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:linkDebugFrameworkIos'.
> Process 'command '/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:linkDebugFrameworkIos'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:192)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1092)
        at org.jetbrains.kotlin.compilerRunner.KonanCliRunner.run(KotlinNativeToolRunner.kt:127)
        at org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile.compile(KotlinNativeTasks.kt:296)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more


* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed
```

**Comment by e5l** [comment]
Could you check for `enableFeaturePreview('GRADLE_METADATA')` in `settings.gradle`?

btw. gradle version should be 4.7

**Comment by MohamedTaher** [comment]
Hi @e5l, After adding this line `enableFeaturePreview('GRADLE_METADATA') `in `settings.gradle` and syncing the gradle, I get this 
```
CONFIGURE SUCCESSFUL in 35s
Could not resolve com.jakewharton.timber:timberNative:5.0.0-k1.3.0-a1.
Could not resolve io.ktor:ktor-client-core-ios:1.0.0.
Could not resolve io.ktor:ktor-client-ios:1.0.0.
Could not resolve io.ktor:ktor-client-json-ios:1.0.0.
Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.0.0.
Could not resolve org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.9.1.
```

then I got this error when I tried to build the IOS project in Xcode
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by uncledoc** [comment]
I had the same problem with `:app:linkDebugFrameworkIos` but solution with `enableFeaturePreview('GRADLE_METADATA')` works for me well! Thanks!

**Comment by ImanX** [comment]
I had the same problem, I added `enableFeaturePreview('GRADLE_METADATA')` in `setting.gradle` and I downgraded gradle version to `4.7`.

**Comment by e5l** [comment]
@MohamedTaher, it looks like you build with JDK 11 version. 
Unfortunately, Gradle 4.7 doesn't support it.

It looks like the problem related to metadata is solved.

**Comment by ForteInformationSolutions** [comment]
Hi, what did actually solve this issue? I have been getting same errors, although I have bit different structure of project I think.
I have already added enableFeaturePreview('GRADLE_METADATA') and done everything suggested, downgrading to 4.7 gradle. But still not working.

I have sharedlibrary and that also has build.gradle, there is app build gradle and obviously project level build gradle, if possible could you guide me bit on this.

**Comment by e5l** [comment]
We update all our libraries to Gradle `4.10`, could you recheck with it?

**Comment by MohamedTaher** [comment]
Hi @e5l 
After upgrading ktor to version 1.1.3 and using Gradle 4.10, I got this error when I tried to build the IOS project in Xcode

```
Parallel execution is an incubating feature.

> Configure project :sharedlibrary
Kotlin Multiplatform Projects are an experimental feature.

> Task :sharedlibrary:linkMainDebugFrameworkIos_x86_64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':sharedlibrary:ios_x86_64CompileKlibraries'.
> Could not find io.ktor:ktor-client-core-ios:1.1.3.
  Searched in the following locations:
    - https://dl.google.com/dl/android/maven2/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://dl.google.com/dl/android/maven2/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - https://jcenter.bintray.com/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://jcenter.bintray.com/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - https://kotlin.bintray.com/kotlinx/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://kotlin.bintray.com/kotlinx/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - https://dl.bintray.com/kodein-framework/Kodein-DI/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://dl.bintray.com/kodein-framework/Kodein-DI/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - https://dl.bintray.com/touchlabpublic/kotlin/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.pom
    - https://dl.bintray.com/touchlabpublic/kotlin/io/ktor/ktor-client-core-ios/1.1.3/ktor-client-core-ios-1.1.3.jar
    - file:/Users/InnoLabs/.konan/kotlin-native-macos-1.1.1/klib/common/ktor-client-core-ios
  Required by:
      project :sharedlibrary
> Could not find io.ktor:ktor-client-json-ios:1.1.3.
  Searched in the following locations:
    - https://dl.google.com/dl/android/maven2/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://dl.google.com/dl/android/maven2/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - https://jcenter.bintray.com/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://jcenter.bintray.com/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - https://kotlin.bintray.com/kotlinx/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://kotlin.bintray.com/kotlinx/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - https://dl.bintray.com/kodein-framework/Kodein-DI/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://dl.bintray.com/kodein-framework/Kodein-DI/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - https://dl.bintray.com/touchlabpublic/kotlin/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.pom
    - https://dl.bintray.com/touchlabpublic/kotlin/io/ktor/ktor-client-json-ios/1.1.3/ktor-client-json-ios-1.1.3.jar
    - file:/Users/InnoLabs/.konan/kotlin-native-macos-1.1.1/klib/common/ktor-client-json-ios
  Required by:
      project :sharedlibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed
Command PhaseScriptExecution failed with a nonzero exit code

```

**Comment by e5l** [comment]
The `ios` artifacts renamed in `1.1.1`. Please check the migration guide: https://ktor.io/quickstart/migration/1.1.1.html

**Comment by MohamedTaher** [comment]
After renaming, I get a new error when I tried to build the IOS project in Xcode

```
> Task :sharedlibrary:linkMainDebugFrameworkIos_x86_64
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-3-darwin-ios_sim.tar.gz (170.4 kiB/170.4 kiB). Done.
Extracting dependency: /var/root/.konan/cache/libffi-3.2.1-3-darwin-ios_sim.tar.gz into /var/root/.konan/dependencies
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:3:8: error: unresolved reference: io
import io.ktor.client.HttpClient
       ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:4:8: error: unresolved reference: io
import io.ktor.client.request.get
       ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:5:8: error: unresolved reference: io
import io.ktor.client.request.url
       ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:6:8: error: unresolved reference: io
import io.ktor.http.Url
       ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:7:16: error: unresolved reference: coroutines
import kotlinx.coroutines.CoroutineDispatcher
               ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:8:16: error: unresolved reference: coroutines
import kotlinx.coroutines.GlobalScope
               ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:9:16: error: unresolved reference: coroutines
import kotlinx.coroutines.launch
               ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:10:16: error: unresolved reference: serialization
import kotlinx.serialization.ImplicitReflectionSerializer
               ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:12:44: error: expected property 'ApplicationDispatcher' has no actual declaration in module 
The following declaration is incompatible because return type is different:
    internal actual val ApplicationDispatcher: [ERROR : CoroutineDispatcher]

internal expect val ApplicationDispatcher: CoroutineDispatcher
                                           ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:12:44: error: unresolved reference: CoroutineDispatcher
internal expect val ApplicationDispatcher: CoroutineDispatcher
                                           ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:14:2: error: unresolved reference: ImplicitReflectionSerializer
@ImplicitReflectionSerializer
 ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:17:26: error: unresolved reference: HttpClient
    private val client = HttpClient()
                         ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:19:19: error: unresolved reference: Url
    var address = Url("https://tools.ietf.org/rfc/rfc1866.txt")
                  ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:22:9: error: unresolved reference: GlobalScope
        GlobalScope.apply {
        ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:23:13: error: unresolved reference: launch
            launch(ApplicationDispatcher) {
            ^
sharedlibrary/src/commonMain/Kotlin/AppApi.kt:25:21: error: unresolved reference: url
                    url(this@AppApi.address.toString())
                    ^
sharedlibrary/src/commonMain/Kotlin/common.kt:3:16: error: unresolved reference: coroutines
import kotlinx.coroutines.GlobalScope
               ^
sharedlibrary/src/iosMain/kotlin/actual.kt:4:16: error: unresolved reference: coroutines
import kotlinx.coroutines.*
               ^
sharedlibrary/src/iosMain/kotlin/actual.kt:7:44: error: actual property 'ApplicationDispatcher' has no corresponding expected declaration
The following declaration is incompatible because return type is different:
    internal expect val ApplicationDispatcher: [ERROR : CoroutineDispatcher]

internal actual val ApplicationDispatcher: CoroutineDispatcher = NsQueueDispatcher(dispatch_get_main_queue())
                                           ^
sharedlibrary/src/iosMain/kotlin/actual.kt:7:44: error: unresolved reference: CoroutineDispatcher
internal actual val ApplicationDispatcher: CoroutineDispatcher = NsQueueDispatcher(dispatch_get_main_queue())
                                           ^
sharedlibrary/src/iosMain/kotlin/actual.kt:11:5: error: unresolved reference: CoroutineDispatcher
) : CoroutineDispatcher() {
    ^
sharedlibrary/src/iosMain/kotlin/actual.kt:12:5: error: 'dispatch' overrides nothing
    override fun dispatch(context: CoroutineContext, block: Runnable) {
    ^
sharedlibrary/src/iosMain/kotlin/actual.kt:12:61: error: unresolved reference: Runnable
    override fun dispatch(context: CoroutineContext, block: Runnable) {
                                                            ^

> Task :sharedlibrary:linkMainDebugFrameworkIos_x86_64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sharedlibrary:linkMainDebugFrameworkIos_x86_64'.
> Process 'command '/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

```

You can check AppApi.kt file from [here](https://github.com/MohamedTaher/Multiplatform-Project-iOS-and-Android/blob/master/MppTry1/sharedlibrary/src/iosMain/kotlin/actual.kt)

**Comment by MarcinMoskala** [comment]
Is there any way to fix it without downgrading Gradle? This is a huge blocker if to use Ktor Client on multiplatform we need to use such an old Gradle version.
