### ISSUE TITLE
Ktor 1.1.0 can't install features anymore

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#829]
### Ktor Version
1.1.0
Kotlin Version 1.3.11

### JVM Version, Operating System and Relevant Context
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

### Code
```Kotlin
import com.auth0.jwk.JwkProviderBuilder
import com.auth0.jwt.JWT
import com.auth0.jwt.JWTVerifier
import com.auth0.jwt.algorithms.Algorithm
import com.fasterxml.jackson.core.util.DefaultIndenter
import com.fasterxml.jackson.core.util.DefaultPrettyPrinter
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import io.ktor.application.Application
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.auth.Authentication
import io.ktor.auth.authenticate
import io.ktor.auth.authentication
import io.ktor.auth.jwt.JWTPrincipal
import io.ktor.auth.jwt.jwt
import io.ktor.features.CallLogging
import io.ktor.features.ContentNegotiation
import io.ktor.features.DefaultHeaders
import io.ktor.jackson.jackson
import io.ktor.response.respondText
import io.ktor.routing.Routing
import io.ktor.routing.get
import io.ktor.routing.post
import io.ktor.routing.route
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

object EdgeApplication {
    @JvmStatic fun main(args: Array<String>) {
        embeddedServer(Netty, port = 8080,
            module = Application::jwtApplication
        ).start(wait = true)
    }
}

fun Application.jwtApplication() {
    val issuer = environment.config.property("jwt.domain").getString()
    val audience = environment.config.property("jwt.audience").getString()
    val realm = environment.config.property("jwt.realm").getString()
    
    install(Authentication) {
        val jwtVerifier = makeJwtVerifier(issuer, audience)
        jwt {
            verifier(jwtVerifier)
            this.realm = realm
            validate { credential ->
                if (credential.payload.audience.contains(audience))
                    JWTPrincipal(credential.payload)
                else
                    null
            }
        }
    }

    install(DefaultHeaders)
    install(CallLogging)
    install(ContentNegotiation) {
        jackson {
            configure(SerializationFeature.INDENT_OUTPUT, false)
            registerModule(JavaTimeModule())
        }
    }
    install(Routing) {
        post("/auth") {
        }

        authenticate {
            route("/who") {
                handle {
                    val principal = call.authentication.principal<JWTPrincipal>()
                    val subjectString = principal!!.payload.subject.removePrefix("auth0|")
                    call.respondText("Success, $subjectString")
                }
            }
        }
    }
}

private val algorithm = Algorithm.HMAC256("secret")
private fun makeJwtVerifier(issuer: String, audience: String): JWTVerifier = JWT
    .require(algorithm)
    .withAudience(audience)
    .withIssuer(issuer)
    .build()
```

### Description
Ever since upgrading to 1.1.0, I can no longer resolve the install function in my IDE. I can downgrade back to 1.0.1, and everything is fine, but as soon as I upgrade again to 1.1.0, `install` can no longer be found, which makes most of the other parts of the code unresolve as well. I've tried refreshing all the gradle dependencies, which doesn't seem to fix it either. When compiling with gradle in the command line, the same errors surface as well.

<img width="674" alt="screen shot 2018-12-25 at 2 16 05 am" src="https://user-images.githubusercontent.com/871169/50415825-4fdb6c80-07eb-11e9-89d2-47e79f0b26d4.png">

<img width="501" alt="screen shot 2018-12-24 at 5 14 36 pm" src="https://user-images.githubusercontent.com/871169/50415830-54078a00-07eb-11e9-9110-6712917096f8.png">

**Comment by kobe2000** [comment]
It seems broken dependency, lack of utils, http and more

**Comment by yschimke** [comment]
Is there a known fix, or just wait for 1.1.1?

**Comment by yschimke** [comment]
For me, fix was bringing in

io.ktor:ktor-utils
io.ktor:ktor-utils-jvm
io.ktor:ktor-http
io.ktor:ktor-http-jvm

**Comment by cy6erGn0m** [comment]
This should be fixed in 1.1.1

**Comment by cy6erGn0m** [comment]
Could you please confirm whether it is fixed or not?

**Comment by wem** [comment]
For me 1.1.1 solved this.

**Comment by dygy** [comment]
Still facing it on 1.1.1 with newest idea, newest kotlin plugin, newest gradle, newest ktor plugin. Yes, i did spend 2 hours in installing all of this, just in trying to solve it. I already had ktor projects, but without install() and everything work fine. 
![image](https://user-images.githubusercontent.com/23248488/60911354-9b3b0100-a28b-11e9-9b77-ceb5fa114ff1.png)
